### ISSUE TITLE
The specified module could not be found

### ISSUE THREAD

**Issue by sunyidong945** [ElectronForConstruct/greenworks-prebuilds#570]
Error: The specified module could not be found.
\\?\E:\laya\electron\electron-quick-start-main\node_modules\greenworks\lib\greenworks-win64.node
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1812)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1203:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:1812)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12633)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (E:\laya\electron\electron-quick-start-main\node_modules\greenworks\greenworks.js:17:18)
    at Module._compile (internal/modules/cjs/loader.js:1152:30)
(node:1880) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information

**Comment by Armaldio** [comment]
Hello :wave: 

Can you give me more details about your error ?

**Comment by sunyidong945** [comment]
> Hello 👋
> 
> Can you give me more details about your error ?

in electron project 
npm install greenworks
npm start
then console the errors

**Comment by Armaldio** [comment]
I'm sorry, but you're posting to the wrong repo
Here is the official greeworks repo: https://github.com/greenheartgames/greenworks

**Comment by sunyidong945** [comment]
> I'm sorry, but you're posting to the wrong repo Here is the official greeworks repo: https://github.com/greenheartgames/greenworks

Thank you,but how to use it?
